spring.application.name=traveladviser

spring.datasource.url=jdbc:postgresql://localhost:5432/travel_app
spring.datasource.username=vikacxio
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.security.oauth2.client.registration.google.client-id=Abrakadabra
spring.security.oauth2.client.registration.google.client-secret=Abrakadabra
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.provider.google.issuer-uri=https://accounts.google.com

# JWT Configuration
jwt.secret=MyVeryLongAndSecureJWTSecretKeyThatIsAtLeast64CharactersLongForHS512EncryptionPurpose
jwt.expiration=86400000

