# Split Expense Module Configuration
server.port=8081
splitexpense.api.base-url=${SPLITEXPENSE_API_BASE_URL:http://localhost:8081/api/split-expense}


# MAIN DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5432/splitexpense_app
spring.datasource.username=vikacxio
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# SECOND DATABASE
spring.datasource.travel-app.jdbc-url=jdbc:postgresql://localhost:5432/travel_app
spring.datasource.travel-app.username=vikacxio
spring.datasource.travel-app.password=
spring.datasource.travel-app.driver-class-name=org.postgresql.Driver