-- Generated by import_osm_pois_to_places.py
-- Inserts OSM POIs into `places` and maps derived tags into `place_tags`.
-- Run this SQL in psql.

-- City: Mumbai
INSERT INTO places (name, description, category_id, latitude, longitude, location, avg_rating, total_ratings, price_level, best_season, city, state, country, source, source_id)
VALUES (
  'Mount Carmels Church',
  NULL,
  (SELECT id FROM categories WHERE name = 'Temple' LIMIT 1),
  19.0510021,
  72.8282639,
  ST_MakePoint(72.8282639, 19.0510021)::geography,
  0.0,
  0,
  2,
  'ALL',
  'Mumbai',
  '',
  'India',
  'osm',
  'node/346592564'
)
ON CONFLICT (source, source_id) DO NOTHING;
INSERT INTO place_tags (place_id, tag_id)
SELECT p.id, t.id
FROM places p
JOIN tags t ON TRUE
WHERE p.source = 'osm'
  AND p.source_id = 'node/346592564'
  AND t.name IN ('spiritual', 'historical', 'photography')
ON CONFLICT DO NOTHING;
INSERT INTO places (name, description, category_id, latitude, longitude, location, avg_rating, total_ratings, price_level, best_season, city, state, country, source, source_id)
VALUES (
  'Amphitheatre',
  NULL,
  (SELECT id FROM categories WHERE name = 'Adventure' LIMIT 1),
  19.0425669,
  72.8188717,
  ST_MakePoint(72.8188717, 19.0425669)::geography,
  0.0,
  0,
  2,
  'ALL',
  'Mumbai',
  '',
  'India',
  'osm',
  'node/346611983'
)
ON CONFLICT (source, source_id) DO NOTHING;
INSERT INTO place_tags (place_id, tag_id)
SELECT p.id, t.id
FROM places p
JOIN tags t ON TRUE
WHERE p.source = 'osm'
  AND p.source_id = 'node/346611983'
  AND t.name IN ('adventure', 'outdoor', 'photography')
ON CONFLICT DO NOTHING;
INSERT INTO places (name, description, category_id, latitude, longitude, location, avg_rating, total_ratings, price_level, best_season, city, state, country, source, source_id)
VALUES (
  'Castella de Aguada',
  NULL,
  (SELECT id FROM categories WHERE name = 'Adventure' LIMIT 1),
  19.0419788,
  72.8184995,
  ST_MakePoint(72.8184995, 19.0419788)::geography,
  0.0,
  0,
  2,
  'ALL',
  'Mumbai',
  '',
  'India',
  'osm',
  'node/494772647'
)
ON CONFLICT (source, source_id) DO NOTHING;
INSERT INTO place_tags (place_id, tag_id)
SELECT p.id, t.id
FROM places p
JOIN tags t ON TRUE
WHERE p.source = 'osm'
  AND p.source_id = 'node/494772647'
  AND t.name IN ('adventure', 'outdoor', 'photography')
ON CONFLICT DO NOTHING;
INSERT INTO places (name, description, category_id, latitude, longitude, location, avg_rating, total_ratings, price_level, best_season, city, state, country, source, source_id)
VALUES (
  'Kala Qila',
  NULL,
  (SELECT id FROM categories WHERE name = 'Adventure' LIMIT 1),
  19.0509899,
  72.8601653,
  ST_MakePoint(72.8601653, 19.0509899)::geography,
  0.0,
  0,
  2,
  'ALL',
  'Mumbai',
  '',
  'India',
  'osm',
  'node/537762970'
)
ON CONFLICT (source, source_id) DO NOTHING;
INSERT INTO place_tags (place_id, tag_id)
SELECT p.id, t.id
FROM places p
JOIN tags t ON TRUE
WHERE p.source = 'osm'
  AND p.source_id = 'node/537762970'
  AND t.name IN ('adventure', 'outdoor', 'photography')
ON CONFLICT DO NOTHING;
INSERT INTO places (name, description, category_id, latitude, longitude, location, avg_rating, total_ratings, price_level, best_season, city, state, country, source, source_id)
VALUES (
  'माहीम किल्ला',
  NULL,
  (SELECT id FROM categories WHERE name = 'Fort' LIMIT 1),
  19.0420113,
  72.8381267,
  ST_MakePoint(72.8381267, 19.0420113)::geography,
  0.0,
  0,
  2,
  'ALL',
  'Mumbai',
  '',
  'India',
  'osm',
  'node/537766323'
)
ON CONFLICT (source, source_id) DO NOTHING;
INSERT INTO place_tags (place_id, tag_id)
SELECT p.id, t.id
FROM places p
JOIN tags t ON TRUE
WHERE p.source = 'osm'
  AND p.source_id = 'node/537766323'
  AND t.name IN ('historical', 'photography')
ON CONFLICT DO NOTHING;
INSERT INTO places (name, description, category_id, latitude, longitude, location, avg_rating, total_ratings, price_level, best_season, city, state, country, source, source_id)
VALUES (
  'Jain Derasar (Temple)',
  NULL,
  (SELECT id FROM categories WHERE name = 'Temple' LIMIT 1),
  19.1008565,
  72.8416507,
  ST_MakePoint(72.8416507, 19.1008565)::geography,
  0.0,
  0,
  2,
  'ALL',
  'Mumbai',
  '',
  'India',
  'osm',
  'node/621556193'
)
ON CONFLICT (source, source_id) DO NOTHING;
INSERT INTO place_tags (place_id, tag_id)
SELECT p.id, t.id
FROM places p
JOIN tags t ON TRUE
WHERE p.source = 'osm'
  AND p.source_id = 'node/621556193'
  AND t.name IN ('spiritual', 'historical', 'photography')
ON CONFLICT DO NOTHING;
INSERT INTO places (name, description, category_id, latitude, longitude, location, avg_rating, total_ratings, price_level, best_season, city, state, country, source, source_id)
VALUES (
  'Neat''s Tongue',
  NULL,
  (SELECT id FROM categories WHERE name = 'Mountain' LIMIT 1),
  19.0300345,
  72.9168629,
  ST_MakePoint(72.9168629, 19.0300345)::geography,
  0.0,
  0,
  2,
  'ALL',
  'Mumbai',
  '',
  'India',
  'osm',
  'node/632352284'
)
ON CONFLICT (source, source_id) DO NOTHING;
INSERT INTO place_tags (place_id, tag_id)
SELECT p.id, t.id
FROM places p
JOIN tags t ON TRUE
WHERE p.source = 'osm'
  AND p.source_id = 'node/632352284'
  AND t.name IN ('adventure', 'nature_lover', 'outdoor', 'photography')
ON CONFLICT DO NOTHING;
INSERT INTO places (name, description, category_id, latitude, longitude, location, avg_rating, total_ratings, price_level, best_season, city, state, country, source, source_id)
VALUES (
  'Shiv Temple',
  NULL,
  (SELECT id FROM categories WHERE name = 'Temple' LIMIT 1),
  19.1243128,
  72.8360841,
  ST_MakePoint(72.8360841, 19.1243128)::geography,
  0.0,
  0,
  2,
  'ALL',
  'Mumbai',
  '',
  'India',
  'osm',
  'node/695630140'
)
ON CONFLICT (source, source_id) DO NOTHING;
INSERT INTO place_tags (place_id, tag_id)
SELECT p.id, t.id
FROM places p
JOIN tags t ON TRUE
WHERE p.source = 'osm'
  AND p.source_id = 'node/695630140'
  AND t.name IN ('spiritual', 'historical', 'photography')
ON CONFLICT DO NOTHING;
INSERT INTO places (name, description, category_id, latitude, longitude, location, avg_rating, total_ratings, price_level, best_season, city, state, country, source, source_id)
VALUES (
  'Gilbert Hill',
  NULL,
  (SELECT id FROM categories WHERE name = 'Mountain' LIMIT 1),
  19.1205767,
  72.839801,
  ST_MakePoint(72.839801, 19.1205767)::geography,
  0.0,
  0,
  2,
  'ALL',
  'Mumbai',
  '',
  'India',
  'osm',
  'node/770452913'
)
ON CONFLICT (source, source_id) DO NOTHING;
INSERT INTO place_tags (place_id, tag_id)
SELECT p.id, t.id
FROM places p
JOIN tags t ON TRUE
WHERE p.source = 'osm'
  AND p.source_id = 'node/770452913'
  AND t.name IN ('adventure', 'nature_lover', 'outdoor', 'photography')
ON CONFLICT DO NOTHING;
INSERT INTO places (name, description, category_id, latitude, longitude, location, avg_rating, total_ratings, price_level, best_season, city, state, country, source, source_id)
VALUES (
  'Antop Hill',
  NULL,
  (SELECT id FROM categories WHERE name = 'Mountain' LIMIT 1),
  19.0207608,
  72.8652556,
  ST_MakePoint(72.8652556, 19.0207608)::geography,
  0.0,
  0,
  2,
  'ALL',
  'Mumbai',
  '',
  'India',
  'osm',
  'node/771136229'
)
ON CONFLICT (source, source_id) DO NOTHING;
INSERT INTO place_tags (place_id, tag_id)
SELECT p.id, t.id
FROM places p
JOIN tags t ON TRUE
WHERE p.source = 'osm'
  AND p.source_id = 'node/771136229'
  AND t.name IN ('adventure', 'nature_lover', 'outdoor', 'photography')
ON CONFLICT DO NOTHING;
INSERT INTO places (name, description, category_id, latitude, longitude, location, avg_rating, total_ratings, price_level, best_season, city, state, country, source, source_id)
VALUES (
  'Aarey Picnic Spot',
  NULL,
  (SELECT id FROM categories WHERE name = 'Park' LIMIT 1),
  19.1366368,
  72.8822677,
  ST_MakePoint(72.8822677, 19.1366368)::geography,
  0.0,
  0,
  2,
  'ALL',
  'Mumbai',
  '',
  'India',
  'osm',
  'node/1184067666'
)
ON CONFLICT (source, source_id) DO NOTHING;
INSERT INTO place_tags (place_id, tag_id)
SELECT p.id, t.id
FROM places p
JOIN tags t ON TRUE
WHERE p.source = 'osm'
  AND p.source_id = 'node/1184067666'
  AND t.name IN ('outdoor', 'photography')
ON CONFLICT DO NOTHING;
INSERT INTO places (name, description, category_id, latitude, longitude, location, avg_rating, total_ratings, price_level, best_season, city, state, country, source, source_id)
VALUES (
  'Statue of Saint Sebastian',
  NULL,
  (SELECT id FROM categories WHERE name = 'Historical' LIMIT 1),
  19.051094,
  72.825701,
  ST_MakePoint(72.825701, 19.051094)::geography,
  0.0,
  0,
  2,
  'ALL',
  'Mumbai',
  '',
  'India',
  'osm',
  'node/1282389460'
)
ON CONFLICT (source, source_id) DO NOTHING;
INSERT INTO place_tags (place_id, tag_id)
SELECT p.id, t.id
FROM places p
JOIN tags t ON TRUE
WHERE p.source = 'osm'
  AND p.source_id = 'node/1282389460'
  AND t.name IN ('historical', 'spiritual', 'photography')
ON CONFLICT DO NOTHING;
INSERT INTO places (name, description, category_id, latitude, longitude, location, avg_rating, total_ratings, price_level, best_season, city, state, country, source, source_id)
VALUES (
  'Mancherji Edulji Joshi Statue',
  NULL,
  (SELECT id FROM categories WHERE name = 'Historical' LIMIT 1),
  19.0175495,
  72.8491666,
  ST_MakePoint(72.8491666, 19.0175495)::geography,
  0.0,
  0,
  2,
  'ALL',
  'Mumbai',
  '',
  'India',
  'osm',
  'node/1289231870'
)
ON CONFLICT (source, source_id) DO NOTHING;
INSERT INTO place_tags (place_id, tag_id)
SELECT p.id, t.id
FROM places p
JOIN tags t ON TRUE
WHERE p.source = 'osm'
  AND p.source_id = 'node/1289231870'
  AND t.name IN ('historical', 'spiritual', 'photography')
ON CONFLICT DO NOTHING;
INSERT INTO places (name, description, category_id, latitude, longitude, location, avg_rating, total_ratings, price_level, best_season, city, state, country, source, source_id)
VALUES (
  'Omkareshwar Mandir',
  NULL,
  (SELECT id FROM categories WHERE name = 'Temple' LIMIT 1),
  19.1121986,
  72.8508276,
  ST_MakePoint(72.8508276, 19.1121986)::geography,
  0.0,
  0,
  2,
  'ALL',
  'Mumbai',
  '',
  'India',
  'osm',
  'node/1345343347'
)
ON CONFLICT (source, source_id) DO NOTHING;
INSERT INTO place_tags (place_id, tag_id)
SELECT p.id, t.id
FROM places p
JOIN tags t ON TRUE
WHERE p.source = 'osm'
  AND p.source_id = 'node/1345343347'
  AND t.name IN ('spiritual', 'historical', 'photography')
ON CONFLICT DO NOTHING;
INSERT INTO places (name, description, category_id, latitude, longitude, location, avg_rating, total_ratings, price_level, best_season, city, state, country, source, source_id)
VALUES (
  'Holy Family Church',
  NULL,
  (SELECT id FROM categories WHERE name = 'Temple' LIMIT 1),
  19.1152427,
  72.8597103,
  ST_MakePoint(72.8597103, 19.1152427)::geography,
  0.0,
  0,
  2,
  'ALL',
  'Mumbai',
  '',
  'India',
  'osm',
  'node/1345350829'
)
ON CONFLICT (source, source_id) DO NOTHING;
INSERT INTO place_tags (place_id, tag_id)
SELECT p.id, t.id
FROM places p
JOIN tags t ON TRUE
WHERE p.source = 'osm'
  AND p.source_id = 'node/1345350829'
  AND t.name IN ('spiritual', 'historical', 'photography')
ON CONFLICT DO NOTHING;
INSERT INTO places (name, description, category_id, latitude, longitude, location, avg_rating, total_ratings, price_level, best_season, city, state, country, source, source_id)
VALUES (
  'Siddhivinayak Temple',
  NULL,
  (SELECT id FROM categories WHERE name = 'Temple' LIMIT 1),
  19.081512,
  72.9119623,
  ST_MakePoint(72.9119623, 19.081512)::geography,
  0.0,
  0,
  2,
  'ALL',
  'Mumbai',
  '',
  'India',
  'osm',
  'node/1451903346'
)
ON CONFLICT (source, source_id) DO NOTHING;
INSERT INTO place_tags (place_id, tag_id)
SELECT p.id, t.id
FROM places p
JOIN tags t ON TRUE
WHERE p.source = 'osm'
  AND p.source_id = 'node/1451903346'
  AND t.name IN ('spiritual', 'historical', 'photography')
ON CONFLICT DO NOTHING;
INSERT INTO places (name, description, category_id, latitude, longitude, location, avg_rating, total_ratings, price_level, best_season, city, state, country, source, source_id)
VALUES (
  'Shankar Deol',
  NULL,
  (SELECT id FROM categories WHERE name = 'Temple' LIMIT 1),
  19.0285178,
  72.8985148,
  ST_MakePoint(72.8985148, 19.0285178)::geography,
  0.0,
  0,
  2,
  'ALL',
  'Mumbai',
  '',
  'India',
  'osm',
  'node/1495380531'
)
ON CONFLICT (source, source_id) DO NOTHING;
INSERT INTO place_tags (place_id, tag_id)
SELECT p.id, t.id
FROM places p
JOIN tags t ON TRUE
WHERE p.source = 'osm'
  AND p.source_id = 'node/1495380531'
  AND t.name IN ('spiritual', 'historical', 'photography')
ON CONFLICT DO NOTHING;
INSERT INTO places (name, description, category_id, latitude, longitude, location, avg_rating, total_ratings, price_level, best_season, city, state, country, source, source_id)
VALUES (
  'Loop Gallery',
  NULL,
  (SELECT id FROM categories WHERE name = 'Adventure' LIMIT 1),
  19.1037194,
  72.8510068,
  ST_MakePoint(72.8510068, 19.1037194)::geography,
  0.0,
  0,
  2,
  'ALL',
  'Mumbai',
  '',
  'India',
  'osm',
  'node/1579184280'
)
ON CONFLICT (source, source_id) DO NOTHING;
INSERT INTO place_tags (place_id, tag_id)
SELECT p.id, t.id
FROM places p
JOIN tags t ON TRUE
WHERE p.source = 'osm'
  AND p.source_id = 'node/1579184280'
  AND t.name IN ('adventure', 'outdoor', 'photography')
ON CONFLICT DO NOTHING;
INSERT INTO places (name, description, category_id, latitude, longitude, location, avg_rating, total_ratings, price_level, best_season, city, state, country, source, source_id)
VALUES (
  'Datta Mandir',
  NULL,
  (SELECT id FROM categories WHERE name = 'Temple' LIMIT 1),
  19.1038897,
  72.8525248,
  ST_MakePoint(72.8525248, 19.1038897)::geography,
  0.0,
  0,
  2,
  'ALL',
  'Mumbai',
  '',
  'India',
  'osm',
  'node/1579303799'
)
ON CONFLICT (source, source_id) DO NOTHING;
INSERT INTO place_tags (place_id, tag_id)
SELECT p.id, t.id
FROM places p
JOIN tags t ON TRUE
WHERE p.source = 'osm'
  AND p.source_id = 'node/1579303799'
  AND t.name IN ('spiritual', 'historical', 'photography')
ON CONFLICT DO NOTHING;
INSERT INTO places (name, description, category_id, latitude, longitude, location, avg_rating, total_ratings, price_level, best_season, city, state, country, source, source_id)
VALUES (
  'Hanuman Mandir',
  NULL,
  (SELECT id FROM categories WHERE name = 'Temple' LIMIT 1),
  19.1038099,
  72.853807,
  ST_MakePoint(72.853807, 19.1038099)::geography,
  0.0,
  0,
  2,
  'ALL',
  'Mumbai',
  '',
  'India',
  'osm',
  'node/1579337883'
)
ON CONFLICT (source, source_id) DO NOTHING;
INSERT INTO place_tags (place_id, tag_id)
SELECT p.id, t.id
FROM places p
JOIN tags t ON TRUE
WHERE p.source = 'osm'
  AND p.source_id = 'node/1579337883'
  AND t.name IN ('spiritual', 'historical', 'photography')
ON CONFLICT DO NOTHING;
INSERT INTO places (name, description, category_id, latitude, longitude, location, avg_rating, total_ratings, price_level, best_season, city, state, country, source, source_id)
VALUES (
  'Shri Dandeshwar Shankar Mandir',
  NULL,
  (SELECT id FROM categories WHERE name = 'Temple' LIMIT 1),
  19.074692,
  72.8235279,
  ST_MakePoint(72.8235279, 19.074692)::geography,
  0.0,
  0,
  2,
  'ALL',
  'Mumbai',
  '',
  'India',
  'osm',
  'node/1641731964'
)
ON CONFLICT (source, source_id) DO NOTHING;
INSERT INTO place_tags (place_id, tag_id)
SELECT p.id, t.id
FROM places p
JOIN tags t ON TRUE
WHERE p.source = 'osm'
  AND p.source_id = 'node/1641731964'
  AND t.name IN ('spiritual', 'historical', 'photography')
ON CONFLICT DO NOTHING;
INSERT INTO places (name, description, category_id, latitude, longitude, location, avg_rating, total_ratings, price_level, best_season, city, state, country, source, source_id)
VALUES (
  'Samyukta Maharashtra Daalan',
  NULL,
  (SELECT id FROM categories WHERE name = 'Museum' LIMIT 1),
  19.0279945,
  72.8365824,
  ST_MakePoint(72.8365824, 19.0279945)::geography,
  0.0,
  0,
  2,
  'ALL',
  'Mumbai',
  '',
  'India',
  'osm',
  'node/1646526516'
)
ON CONFLICT (source, source_id) DO NOTHING;
INSERT INTO place_tags (place_id, tag_id)
SELECT p.id, t.id
FROM places p
JOIN tags t ON TRUE
WHERE p.source = 'osm'
  AND p.source_id = 'node/1646526516'
  AND t.name IN ('museum', 'indoor', 'historical', 'photography')
ON CONFLICT DO NOTHING;
INSERT INTO places (name, description, category_id, latitude, longitude, location, avg_rating, total_ratings, price_level, best_season, city, state, country, source, source_id)
VALUES (
  'Jain Temple',
  NULL,
  (SELECT id FROM categories WHERE name = 'Temple' LIMIT 1),
  19.1032034,
  72.8464716,
  ST_MakePoint(72.8464716, 19.1032034)::geography,
  0.0,
  0,
  2,
  'ALL',
  'Mumbai',
  '',
  'India',
  'osm',
  'node/1803674320'
)
ON CONFLICT (source, source_id) DO NOTHING;
INSERT INTO place_tags (place_id, tag_id)
SELECT p.id, t.id
FROM places p
JOIN tags t ON TRUE
WHERE p.source = 'osm'
  AND p.source_id = 'node/1803674320'
  AND t.name IN ('spiritual', 'historical', 'photography')
ON CONFLICT DO NOTHING;
INSERT INTO places (name, description, category_id, latitude, longitude, location, avg_rating, total_ratings, price_level, best_season, city, state, country, source, source_id)
VALUES (
  'Jain Temple',
  NULL,
  (SELECT id FROM categories WHERE name = 'Temple' LIMIT 1),
  19.1122716,
  72.8266876,
  ST_MakePoint(72.8266876, 19.1122716)::geography,
  0.0,
  0,
  2,
  'ALL',
  'Mumbai',
  '',
  'India',
  'osm',
  'node/1803679093'
)
ON CONFLICT (source, source_id) DO NOTHING;
INSERT INTO place_tags (place_id, tag_id)
SELECT p.id, t.id
FROM places p
JOIN tags t ON TRUE
WHERE p.source = 'osm'
  AND p.source_id = 'node/1803679093'
  AND t.name IN ('spiritual', 'historical', 'photography')
ON CONFLICT DO NOTHING;
INSERT INTO places (name, description, category_id, latitude, longitude, location, avg_rating, total_ratings, price_level, best_season, city, state, country, source, source_id)
VALUES (
  'Shri Krishna Mandir',
  NULL,
  (SELECT id FROM categories WHERE name = 'Temple' LIMIT 1),
  19.0514705,
  72.86736,
  ST_MakePoint(72.86736, 19.0514705)::geography,
  0.0,
  0,
  2,
  'ALL',
  'Mumbai',
  '',
  'India',
  'osm',
  'node/2134898672'
)
ON CONFLICT (source, source_id) DO NOTHING;
INSERT INTO place_tags (place_id, tag_id)
SELECT p.id, t.id
FROM places p
JOIN tags t ON TRUE
WHERE p.source = 'osm'
  AND p.source_id = 'node/2134898672'
  AND t.name IN ('spiritual', 'historical', 'photography')
ON CONFLICT DO NOTHING;
